### ISSUE TITLE
Static task does not copy directories – only files (blendid)

### ISSUE THREAD

**Issue by NoLooseEnds** [vigetlabs/gulp-starter#384]
Static task does not copy directories – only files.  If I put a directory in "static" it does not get copied. This was not the case with "gulp-starter".

Is this in error, or is there another way to handle "static" directories. In this particular case it is json data for a table.

**Comment by greypants** [comment]
Man. I always forget the difference between `/**` and `/**/*`. I thought the latter was suppsoed to include directories... dos it need to be switched back? 

gulp-starter `master` has it the first way: https://github.com/vigetlabs/gulp-starter/blob/master/gulpfile.js/tasks/static.js#L8
D'oh! It's because I used `path.resolve` here instead of `path.join`: https://github.com/vigetlabs/gulp-starter/blob/blendid/gulpfile.js/tasks/static.js#L11

Resolve ignores the glob pattern I believe. WILL FIX!

**Comment by greypants** [comment]
fixed, and pushed up a `4.0.0-blendid-beta-19` release. `yarn upgrade blendid` should make everything better.

**Comment by NoLooseEnds** [comment]
Thanks. But don't look like the npm package is updated. I updated the static.js file manually, but it still did not copy the directory.

Does it work for you?

**Comment by NoLooseEnds** [comment]
I got it to update through yarn now (verified that static.js had changed), but it still does not copy directories.

**Comment by greypants** [comment]
☹️

**Comment by greypants** [comment]
I can't reproduce this. I'm running `blendid@4.0.0-blendid-beta-19`. Can you give any more details? What do your config files look like? `static` in `task-config.js` can either just be set to `true`, or you can pass it an object of extensions to limit what's included and watched.

```js
static: true
```

or

```js
static: {
    extensions: ["png", "svg", "xml", "json", "ico"] // etc...
 }
```

**Comment by NoLooseEnds** [comment]
Thanks for checking. It's weird. 

I started a new project now, and there it works fine. So you fixed it, the error is somewhere on my end.

As far as I know, I have not done anything special.
I installed beta 18, and then upgraded to beta 19.

**Commands:**
```
yarn init
yarn add blendid
yarn run blendid -- init
yarn add susy
yarn add breakpoint-sass
yarn add font-awesome
yarn upgrade blendid
yarn run blendid
```

**Edits in config/task-config.js**
Added modules.js (this task, regardless if it's in a separate file or app.js, breaks the JS scripts.)
```
  javascripts: {
    entries: {
      app: ["./app.js"],
      modules: ["./modules.js"]
    },
    extensions: ["js", "json"],
    extractSharedJs: false
  },
```
Changed "includedPaths" till a generic one, so I can add ie. susy, etc. without editing this file again.
(Could that be a thing to do as standard btw?)
```
  stylesheets: {
    autoprefixer: {
      browsers: ["last 3 version"]
    },
    sass: {
      indentedSyntax: true,
      includePaths: [
        "./node_modules"
      ]
    },
    extensions: ["sass", "scss", "css"]
  },
```
Added .njk extension, since I prefer .njk for nunjucks.
```
  html: {
    dataFile: "data/global.json",
    htmlmin: {
      collapseWhitespace: true
    },
    extensions: ["html", "njk", "json"],
    excludeFolders: ["layouts", "shared", "macros", "data"]
  },
```

**Comment by greypants** [comment]
weird. When in doubt... nuke all the things: 

```
rm -rf node_modules && yarn install
```

> Changed "includedPaths" till a generic one, so I can add ie. susy, etc. without editing this file again. (Could that be a thing to do as standard btw?)

Oh I like that. Pull Request that!

**Comment by NoLooseEnds** [comment]
Did a pull request. Hopefully it goes through. (I'm new to this, as you probably figured out) :)
